### ISSUE TITLE
建议添加歌词多行显示功能

### ISSUE THREAD

**Issue by FlyRenxing** [huangguacucumber/subtitle#2]
如题。歌词双行/多行显示可能更方便卡拉OK的那种模式。希望可以考虑一下捏。

下面是我在很久之前fork您项目时修改的双行显示版本，加入了出场和退场的随机动画，有些小BUG。您可以参考一下。
网址：https://subtitle.renxing.cc/
主要修改了App.vue
[App.txt](https://github.com/huangguacucumber/subtitle/files/10576552/App.txt)

**Comment by huangguacucumber** [comment]
很棒捏！
目前添加了显示下一句的功能，应该是能够满足你的提议的
随机动画目前是不考虑的，因为用户在使用时应当使其有预测歌词出现位置的能力，可以完美的接续歌词，将精神投入到「唱歌」这件事本身，而不是专注于「歌词在哪里」

**Comment by FlyRenxing** [comment]
很高兴您能采纳我的建议！其实我的灵感来自很久以前看到的透明音响：Lyiew Pro3和MORRORART。他们的歌词动效及风格本人十分喜欢😂。在 2023年2月11日，14:25，高 晟捷 ***@***.***> 写道：﻿
Closed #2 as completed.

**Comment by huangguacucumber** [comment]
> 很高兴您能采纳我的建议！其实我的灵感来自很久以前看到的透明音响：Lyiew Pro3和MORRORART。他们的歌词动效及风格本人十分喜欢😂。在 2023年2月11日，14:25，高 晟捷 ***@***.***> 写道：﻿ Closed #2 as completed. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

刚才去看了下你提到的音响的动画，是很棒的作品
但它们的动效的确是不适合本项目的，它们的动画大多有很夸张的移动/形变，本身是不适合快速阅读的
且音响的定位是家居摆件，而本项目主要是让没有听过这首歌的人能够理解歌词意思，避免出现遇到发音不清/外文 时只能听曲，感受不到作词人通过歌词传达出的力量。吃面不吃蒜，味道少一半。听歌不听词，知浅不能思。（瞎编的我也不喜欢吃蒜
音响的大部分使用场景是在用户听过一遍歌之后再放，在第一遍时想去理解歌词的用户肯定会去看，不想去理解的用户即使音响会显示歌词他也不会刻意去看
所以本项目不会使用音响那种过于艺术的动画，主要在于目标用户不一样
谢谢你的建议！
